### ISSUE TITLE
Tumbleweed images are no longer being updated.

### ISSUE THREAD

**Issue by hurricanehrndz** [openSUSE/docker-containers#38]
https://hub.docker.com/r/opensuse/amd64/tags/  - 25 days since last update\
https://hub.docker.com/r/library/opensuse/tags/ - 19 days ago

Issues with Kiwi:
https://build.opensuse.org/project/show/Virtualization:containers:images:openSUSE-Tumbleweed
No new kiwi builds since Jan 05, 17.
http://download.opensuse.org/repositories/Virtualization:/containers:/images:/openSUSE-Tumbleweed/images/

**Comment by hurricanehrndz** [comment]
seems like the following package is now missing from factory
```
 this-is-only-for-build-envs
```

**Comment by davidcassany** [comment]
@hurricanehrndz right, this is because the Kiwi version has been updated and now build service requires `systemd` and `udev` to be present in the virtual machine that launches Kiwi. Adding `systemd` and `udev` requirement on project configuration (just for the build environment, the docker image remains unchanged) solved the issue.

Thanks for reporting it.

**Comment by flavio** [comment]
Closing as it has been fixed.
